---
version: "3.7"

services:
  mongodb:
    image: bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=whatsup
      - MONGODB_PASSWORD=whatsup
      - MONGODB_DATABASE=whatsup
    volumes:
      - mongodb:/bitnami/monogodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    image: bitnami/postgresql:15
    container_name: postgres
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=bitnami_keycloak
      - POSTGRESQL_USERNAME=bn_keycloak
    volumes:
      - postgres:/bitnami/postgresql
    healthcheck:
      test: pg_isready -d bitnami_keycloak -U bn_keycloak
      interval: 10s
      timeout: 10s
      retries: 5

  keycloak:
    image: bitnami/keycloak:22
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT_NUMBER=5432
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongodb:
  postgres:
