on:
  push:
    branches:
      - master
  pull_request:

name: CI
env:
  RUSTFLAGS: "-Dwarnings"


jobs:

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cd backend && cargo clippy --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Rustfmt
        run: cd backend && cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd backend && cargo build --release