on: [ push, pull_request ]

name: CI

jobs:

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cd backend && cargo clippy --all-targets --all-features -Dwarnings
